vdeploy:
	ansible-playbook vdeploy.playbook -k -K -i hosts

updates: 
	ansible-playbook updates.playbook -k -K -i hosts

deploy:
	ansible-playbook deploy.playbook -k -K -i hosts

web-install:
	ansible-playbook web-install.playbook -k -K -i hosts
