---
# tasks file for breadboard-compile-source
- name: "Download {{ name }}"
  get_url:
    url: "{{ download_url }}/{{ download_filename }}"
    dest: "{{ build_dir }}/{{ download_filename }}"
    checksum: "{{ checksum }}"
- name: "Extract {{ name }}"
  command: "tar xvf {{ download_filename }}"
  args:
    chdir: "{{ build_dir }}"
- name: "Configure {{ name }}"
  command: "./configure --prefix={{ prefix }} {{ extra_configure_args }}"
  args:
    chdir: "{{ build_dir }}/{{ extract_dir }}"
- name: "Build {{ name }}"
  command: make
  args:
    chdir: "{{ build_dir }}/{{ extract_dir }}"
- name: "Install {{ name }}"
  command: make install
  args:
    chdir: "{{ build_dir }}/{{ extract_dir }}"

